# Site settings
title: "Mihail Stoica"
description: "software engineer focused on distributed systems, web based n-tiered Java, Spring Boot architectures, domain driven design, event sourcing, CQRS pattern and event-driven design for asynchronous microservices with Apache Kafka"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mihail Stoica"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hello@mihailstoica.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "hello@mihailstoica.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Junior software engineer focused on developing my skills in distributed systems, web based n-tiered Java, Spring architectures, domain driven design, event sourcing, CQRS pattern and event-driven design for asynchronous microservices with Apache Kafka.

<br><br>Prior, I worked for 16 years as a consultant in real estate sector, mostly doing acquisitions and asset management for a family office in Luxembourg. I also have experience in insurance sector as an apprenticeship actuary while studying for a math degree.

<br><br>Being a business centric individual, with a good knowledge of the main economic sectors, I naturally developed a keen interest for software engineering following domain-driven design architecture, event sourcing and CQRS pattern, looking to close the gap between business reality and software code.

<br><br>My job is to translate and break down your business problem into a software problem. Through careful collaboration, strategic thinking, and technical expertise, my role is to know what questions to ask and what answers to accept. My ultimate goal is to provide you with solutions that are efficient, cost-effective, and specifically tailored to your business needs.

<br><br>Knowing the value of a client, in every line of code I write, the customer satisfaction is my highest priority.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
# resume_section_experience:      true
# resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/mihail-stoica/"
  # resume_twitter_url:           "insert Twitter URl here"
  # resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mihail-stoica/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "insert your website URL here"
  # resume_medium_url:            "insert your Medium URL here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Google Analytics
google_analytics: G-ZNTWNKYCVN

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
